In [8]:
# Initializing NumPy array with zero
import numpy as np

n1 = np.zeros((6,7))
n2 = np.zeros((1,2))
print(n1)
#print(n2)
type(n1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


numpy.ndarray

In [11]:
# Initializing NumPy array with same number

import numpy as np
n1 = np.full((2,3),16)
n1


array([[16, 16, 16],
       [16, 16, 16]])

In [14]:
                        # Initializing NumPy array with range

import numpy as np

np1 = np.arange(12,16)#first argument is starting range and second argument is end of the rangeyu8
np2 = np.arange(11,25,2)# third argument is interval of the arange
print(np1)
print(np2)


[12 13 14 15]
[11 13 15 17 19 21 23]


In [30]:
                    # Initializing NumPy array with random number

import numpy as np1

n1 = np1.random.randint(1,14,14)
n1
#n1.shape

array([ 3,  1, 12,  6, 12,  8,  9, 12,  6, 11,  5, 13, 10,  4])

In [25]:
                    #Checking the shape of the NumPy arrays

import numpy as np

n1 = np.array([[1,2,3],[3,12,34],[12,13,32]])
n1.shape

(3, 3)

In [11]:
                                # Joining NumPy Array

import numpy as np

s1 = np.array([1,2,3,4,5])
s2 = np.array([10,20,30,40,50])
s3 = np.vstack((s1,s2)) # vertical Join
s4 = np.hstack((s1,s2)) # Horizontal Join
s5 = np.column_stack((s1,s2)) # Join the array in column(vertical)
s6 = np.row_stack((s1,s2))  # Join the array in row(horizontal)
print((s6))
print(s3)
#print(s4)

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[[ 1  2  3  4  5]
 [10 20 30 40 50]]


In [15]:
               # Numpy Intersection and Difference
    
import numpy as np

s1 = np.array([12,11,23,21,34])
s2 = np.array([21,23,22,45,56])

s3 = np.intersect1d(s1,s2) # Intersection method intersect1d()

s3


s3 = np.setdiff1d(s1,s2) # difference from s1 to s2

s3


s3 = np.setdiff1d(s2,s1) # diffence from s2 to s1

s3

array([22, 45, 56])

In [25]:
                        # NumPy Array Mathematics
import numpy as np

n1 = np.array([10,11,12,13,15])
n2 = np.array([10,20,30,40,50])


s = np.sum([n1,n2]) # addition is perform by sum() method

s = np.subtract(n2,n1) # substraction is performed by subtract() method

s

# n1 = n1+1 # Basic addition in array

# n1 = n1-5 # Basic Substraction in array

n1 = n1*3 # Basic multiplication in array

n1 = n1/2.4 # Basic Divison in array
n1

array([12.5 , 13.75, 15.  , 16.25, 18.75])

In [30]:
                # NumPy Math Functions
    
import numpy as np

n1  = np.array([121.1,1233,213])

#np.mean(n1)  # Mean funtion mean()

#np.median(n1) # median Funtion median()

np.std(n1) # Standered Deviation function std()



503.8923187436864

In [35]:
                # Numpy array Save & Load 
    
import numpy as np

n1 = np.array([1,2,3,4,5,6,7,8,9])

#np.save("save_numPy.npy",n1) # Saving the NumPy File 

n2 = np.load("save_numPy.npy") # Loading the Numpy File

n2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])